"""added columns for google sso1

Revision ID: 73bbbdd7046e
Revises: 853a19692c30
Create Date: 2024-01-14 00:24:48.535467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73bbbdd7046e'
down_revision: Union[str, None] = '853a19692c30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('google_auth', 'google_unique_id_for_user',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('google_auth', 'google_unique_id_for_user',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    # ### end Alembic commands ###
