"""added columns for google sso

Revision ID: 853a19692c30
Revises: 5ec15abee07b
Create Date: 2024-01-14 00:20:15.198303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '853a19692c30'
down_revision: Union[str, None] = '5ec15abee07b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('google_auth', sa.Column('google_unique_id_for_user', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('google_auth', 'google_unique_id_for_user')
    # ### end Alembic commands ###
