"""added projects

Revision ID: 8691ea8c7b9a
Revises: 
Create Date: 2024-02-02 00:47:23.812271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8691ea8c7b9a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_scripts',
    sa.Column('project_script_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('script_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.script_id'], ),
    sa.PrimaryKeyConstraint('project_script_id')
    )
    op.create_index(op.f('ix_project_scripts_project_script_id'), 'project_scripts', ['project_script_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_scripts_project_script_id'), table_name='project_scripts')
    op.drop_table('project_scripts')
    # ### end Alembic commands ###
