"""created at to BlacklistedToken

Revision ID: 877daf0806ff
Revises: 7ec584d9947b
Create Date: 2024-02-04 00:51:07.607952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '877daf0806ff'
down_revision: Union[str, None] = '7ec584d9947b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blacklisted_tokens', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blacklisted_tokens', 'created_at')
    # ### end Alembic commands ###
