"""added projects timestamp

Revision ID: b36058ce5256
Revises: 8691ea8c7b9a
Create Date: 2024-02-02 00:48:01.568667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b36058ce5256'
down_revision: Union[str, None] = '8691ea8c7b9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_scripts', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('project_scripts', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_scripts', 'updated_at')
    op.drop_column('project_scripts', 'created_at')
    # ### end Alembic commands ###
