"""first migration

Revision ID: ba04ba7d4202
Revises: 
Create Date: 2023-12-31 23:20:10.198393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba04ba7d4202'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plans',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('plan_name', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('billing_cycle', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_index(op.f('ix_subscription_plans_plan_id'), 'subscription_plans', ['plan_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('other_info', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('apple_auth',
    sa.Column('apple_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('other_apple_data', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('apple_id')
    )
    op.create_index(op.f('ix_apple_auth_apple_id'), 'apple_auth', ['apple_id'], unique=False)
    op.create_table('failed_transactions',
    sa.Column('failed_transaction_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('failed_transaction_id')
    )
    op.create_index(op.f('ix_failed_transactions_failed_transaction_id'), 'failed_transactions', ['failed_transaction_id'], unique=False)
    op.create_table('google_auth',
    sa.Column('google_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('other_google_data', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('google_id')
    )
    op.create_index(op.f('ix_google_auth_google_id'), 'google_auth', ['google_id'], unique=False)
    op.create_table('scripts',
    sa.Column('script_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('last_modified_at', sa.DateTime(), nullable=True),
    sa.Column('logline', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('script_id')
    )
    op.create_index(op.f('ix_scripts_script_id'), 'scripts', ['script_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.plan_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('subscription_id')
    )
    op.create_index(op.f('ix_subscriptions_subscription_id'), 'subscriptions', ['subscription_id'], unique=False)
    op.create_table('user_activity',
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('activity_type', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('activity_id')
    )
    op.create_index(op.f('ix_user_activity_activity_id'), 'user_activity', ['activity_id'], unique=False)
    op.create_table('user_details',
    sa.Column('user_details_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('other_info', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_details_id')
    )
    op.create_index(op.f('ix_user_details_user_details_id'), 'user_details', ['user_details_id'], unique=False)
    op.create_table('payments',
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.subscription_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_index(op.f('ix_payments_payment_id'), 'payments', ['payment_id'], unique=False)
    op.create_table('script_activity',
    sa.Column('script_activity_id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=True),
    sa.Column('script_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['user_activity.activity_id'], ),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.script_id'], ),
    sa.PrimaryKeyConstraint('script_activity_id')
    )
    op.create_index(op.f('ix_script_activity_script_activity_id'), 'script_activity', ['script_activity_id'], unique=False)
    op.create_table('script_versions',
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('script_id', sa.UUID(), nullable=True),
    sa.Column('version_number', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('script_file_url', sa.String(), nullable=True),
    sa.Column('change_summary', sa.String(), nullable=True),
    sa.Column('modified_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['modified_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.script_id'], ),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_index(op.f('ix_script_versions_version_id'), 'script_versions', ['version_id'], unique=False)
    op.create_index(op.f('ix_script_versions_version_number'), 'script_versions', ['version_number'], unique=False)
    op.create_table('shared_scripts',
    sa.Column('shared_id', sa.UUID(), nullable=False),
    sa.Column('script_id', sa.UUID(), nullable=True),
    sa.Column('shared_with_identifier', sa.String(), nullable=True),
    sa.Column('shared_by_user_id', sa.UUID(), nullable=True),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.Column('permission_level', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.script_id'], ),
    sa.ForeignKeyConstraint(['shared_by_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('shared_id')
    )
    op.create_index(op.f('ix_shared_scripts_shared_id'), 'shared_scripts', ['shared_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shared_scripts_shared_id'), table_name='shared_scripts')
    op.drop_table('shared_scripts')
    op.drop_index(op.f('ix_script_versions_version_number'), table_name='script_versions')
    op.drop_index(op.f('ix_script_versions_version_id'), table_name='script_versions')
    op.drop_table('script_versions')
    op.drop_index(op.f('ix_script_activity_script_activity_id'), table_name='script_activity')
    op.drop_table('script_activity')
    op.drop_index(op.f('ix_payments_payment_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_user_details_user_details_id'), table_name='user_details')
    op.drop_table('user_details')
    op.drop_index(op.f('ix_user_activity_activity_id'), table_name='user_activity')
    op.drop_table('user_activity')
    op.drop_index(op.f('ix_subscriptions_subscription_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_scripts_script_id'), table_name='scripts')
    op.drop_table('scripts')
    op.drop_index(op.f('ix_google_auth_google_id'), table_name='google_auth')
    op.drop_table('google_auth')
    op.drop_index(op.f('ix_failed_transactions_failed_transaction_id'), table_name='failed_transactions')
    op.drop_table('failed_transactions')
    op.drop_index(op.f('ix_apple_auth_apple_id'), table_name='apple_auth')
    op.drop_table('apple_auth')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_subscription_plans_plan_id'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    # ### end Alembic commands ###
