"""updatenow and logline

Revision ID: e7d69ca07be8
Revises: 68b698b0783b
Create Date: 2023-12-30 23:13:33.659492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7d69ca07be8'
down_revision: Union[str, None] = '68b698b0783b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scripts', sa.Column('logline', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scripts', 'logline')
    # ### end Alembic commands ###
