"""added script notes

Revision ID: effd6ca68f54
Revises: ba04ba7d4202
Create Date: 2024-01-01 22:42:45.703287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'effd6ca68f54'
down_revision: Union[str, None] = 'ba04ba7d4202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('script_notes',
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('script_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('note_content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.script_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('note_id')
    )
    op.create_index(op.f('ix_script_notes_note_id'), 'script_notes', ['note_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_script_notes_note_id'), table_name='script_notes')
    op.drop_table('script_notes')
    # ### end Alembic commands ###
